// Code generated by raindrop build, DO NOT EDIT.
import { ActorNamespace, Ai, Annotation, App, KvCache, Logger, MRNObject, ServiceStub, SmartMemory, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AGENT_MEMORY: SmartMemory;
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  API_GATEWAY: ServiceStub<import('../api-gateway/index.js').default>;
  INTELLIGENCE_SERVICE: ServiceStub<import('../intelligence-service/index.js').default>;
  logger: Logger;
  mem: KvCache;
  MEMORY_SERVICE: ActorNamespace<import('../memory-service/index.js').MemoryService>;
  SENTINEL_DB: SqlDatabase;
  STORAGE_SERVICE: ServiceStub<import('../storage-service/index.js').default>;
  tracer: Tracer;
}
